module RailsRefdocs
  module Topics
    class Ruby < Topic
      def name = "ruby"
      def title = "Ruby"
      def source = "https://cache.ruby-lang.org/pub/ruby/ (tarball, rdoc)"

      def locked(lock)
        lock.ruby
      end

      def latest(pin)
        Versions.latest_ruby(pin)
      end

      def fetch(version, stage, work_dir)
        minor = version.split(".").first(2).join(".")
        tarball = File.join(work_dir, "ruby-#{version}.tar.gz")
        src = File.join(work_dir, "ruby-src")
        log "#{version}: downloading the source tarball"
        Http.download("https://cache.ruby-lang.org/pub/ruby/#{minor}/ruby-#{version}.tar.gz", tarball)
        Archive.extract(tarball, src)
        FileUtils.rm_f(tarball)
        log "#{version}: generating API markdown with rdoc (about a minute)"
        Rdoc.generate(src, stage, [ "." ])
      end

      def layout
        <<~MD
          - `ruby/` Ruby core and standard library (default gems included, bundled
            gems such as csv are not).
            - `api/` one file per class/module, generated by rdoc from the release tarball.
            - `pages/` Ruby's own docs converted to Markdown: `syntax/` (language
              syntax: methods, control expressions, pattern matching, refinements),
              `language/`, `NEWS/` (per-release changes), `NEWS.md`, `standard_library.md`.
            - `CLASSES.tsv`, `METHODS.tsv` indexes.
        MD
      end
    end
  end
end
