module RailsRefdocs
  class Readme
    def initialize(reference, topics, command)
      @reference = reference
      @topics = topics.map { |name| Topics.fetch(name) }
      @command = command
    end

    def write
      File.write(@reference.readme, render)
    end

    def render
      [ intro, api_indexes, postgres_pages, layout, hotwire_note ].compact.join
    end

    private

    def names
      @topics.map(&:name)
    end

    def stack
      titles = @topics.map(&:title)
      titles.size < 2 ? titles.join : "#{titles[0..-2].join(", ")} and #{titles.last}"
    end

    def rows
      @topics.map do |topic|
        row = @reference.manifest[topic.name]
        "| `#{topic.name}/` | #{row&.version || "not fetched"} | #{row&.fetched || "-"} | #{topic.source} |\n"
      end.join
    end

    def intro
      <<~MD
        # reference/

        Local, greppable API references and guides for this Ruby on Rails app's
        stack: #{stack}. Everything is Markdown (or SCSS/TSV)
        generated from upstream sources, so `grep`, `cat` and `sed -n` are all
        you need. Generated by [rails-refdocs](https://github.com/Common-Pattern/rails-refdocs).

        Only this README, `TOPICS` and `VERSIONS` are committed. Everything else
        under `reference/` is gitignored. `TOPICS` lists the topics; a topic's
        version is its pin in `TOPICS`, else the version in `Gemfile.lock` (or
        `.ruby-version` for Ruby), else the latest release. On a fresh checkout,
        or when `TOPICS`, `VERSIONS` or `Gemfile.lock` changes, run:

        ```sh
        #{@command} update            # every topic, skips what is current
        #{@command} update rails      # one topic
        #{@command} check             # recorded vs resolved versions, fetches nothing
        #{@command} check --locked    # offline: fails if VERSIONS is behind Gemfile.lock
        #{@command} update --force ruby
        ```

        ## Versions

        | Folder | Version | Fetched (UTC) | Source |
        | --- | --- | --- | --- |
        #{rows}
        Machine-readable copy: `reference/VERSIONS` (TSV: topic, version, fetched, source).

        ## Searching

        Because the topic folders are gitignored, ripgrep (and tools built on it)
        skip them unless told otherwise. In a git worktree the topic folders may be
        symlinks into the main checkout (`#{@command} link`), which `grep -r` and plain
        `rg` do not follow when searching `reference/` as a whole. Use `grep -R`
        or `rg -uuL`:

        ```sh
        grep -Rn 'pattern' reference/
        rg -uuL -n 'pattern' reference/
        ```
      MD
    end

    def api_indexes
      return unless names.include?("ruby") || names.include?("rails")
      <<~'MD'

        Find the API file for a Ruby or Rails class or method through the two TSV
        indexes that sit next to each generated API tree:

        ```sh
        grep -P '^ActiveRecord::Base\t' reference/rails/CLASSES.tsv
        grep -P '#validates\t' reference/rails/METHODS.tsv
        grep -P '^String#gsub\t' reference/ruby/METHODS.tsv
        ```

        - `CLASSES.tsv`: `Full::Name<TAB>api/path.md<TAB>first sentence of its docs`
        - `METHODS.tsv`: `Full::Name#instance_method` or `Full::Name.class_method`, `<TAB>api/path.md`

        Class and module files map namespaces to folders: `ActiveRecord::Base` is
        `reference/rails/api/ActiveRecord/Base.md`, `Net::HTTP` is
        `reference/ruby/api/Net/HTTP.md`. Each API file has the class/module line,
        `Defined in:` source paths, includes/extends, the class docs, then
        `## Constants`, `## Attributes`, `## Class methods` (`### .name`) and
        `## Instance methods` (`### #name`), each method with its signature and a
        `Source:` path in the upstream repo. Methods are documented where they are
        defined: `save` lives in `ActiveRecord/Persistence.md`, not
        `ActiveRecord/Base.md`. Use `METHODS.tsv` or the `Includes:`/`Extends:` lines
        to follow them.
      MD
    end

    def postgres_pages
      return unless names.include?("postgres")
      <<~MD

        PostgreSQL pages keep the names of the official HTML pages
        (`postgresql.org/docs/<major>/<name>.html` is `reference/postgres/docs/<name>.md`).
        `reference/postgres/TITLES.tsv` maps each name to its heading:

        ```sh
        grep -i 'uuid' reference/postgres/TITLES.tsv
        grep -Rn 'uuidv7' reference/postgres/docs
        ```
      MD
    end

    def layout
      "\n## Layout\n\n" + @topics.map(&:layout).join
    end

    def hotwire_note
      return unless names.include?("turbo") || names.include?("stimulus")
      <<~MD

        Turbo and Stimulus site docs are not tagged upstream; their version string
        records the npm package version, the Rails gem version and the site commit.
      MD
    end
  end
end
